[webservers]
web-1 ansible_host=130.193.50.12 fqdn=fhm2mfksbcevigc138ld.auto.internal
web-2 ansible_host=93.77.185.67 fqdn=fhmu5i5f2piahpggdurh.auto.internal

[databases]
main ansible_host=111.88.241.106 fqdn=fhm4k9epum8ibhnnocmm.auto.internal
replica ansible_host=93.77.182.183 fqdn=fhmgudn7ael1fmcfcppn.auto.internal

[storage]
storage ansible_host=158.160.47.74 fqdn=fhm30e2vae38ortd246k.auto.internal
